const fs = require('fs-extra');
const path = require('path');
const PDFDocument = require('pdfkit');
const { createObjectCsvWriter } = require('csv-writer');
const ExcelJS = require('exceljs');
const Video = require('../models/Video');
const UploadReport = require('../models/UploadReport');
const Execution = require('../models/Execution');

class ReportGenerator {
  constructor() {
    this.reportsPath = path.join(__dirname, '../../storage/reports');
    this.ensureDirectories();
  }

  ensureDirectories() {
    fs.ensureDirSync(this.reportsPath);
    fs.ensureDirSync(path.join(this.reportsPath, 'pdf'));
    fs.ensureDirSync(path.join(this.reportsPath, 'csv'));
    fs.ensureDirSync(path.join(this.reportsPath, 'excel'));
  }

  async generateExecutionReport(execution, results) {
    try {
      const reportPath = path.join(
        this.reportsPath,
        'pdf',
        `execution_${execution.executionId}_${Date.now()}.pdf`
      );

      const doc = new PDFDocument({
        size: 'A4',
        margins: {
          top: 50,
          bottom: 50,
          left: 50,
          right: 50
        }
      });

      const stream = fs.createWriteStream(reportPath);
      doc.pipe(stream);

      // Header
      doc.fontSize(20).font('Helvetica-Bold')
         .text('AUTOLIVE Execution Report', { align: 'center' })
         .moveDown();

      // Report metadata
      doc.fontSize(10).font('Helvetica')
         .text(`Report Generated: ${new Date().toLocaleString()}`)
         .text(`Execution ID: ${execution.executionId}`)
         .text(`Workflow: ${execution.workflowName}`)
         .text(`Status: ${execution.status}`)
         .moveDown();

      // Timeline
      doc.fontSize(14).font('Helvetica-Bold')
         .text('Timeline')
         .moveDown(0.5);

      doc.fontSize(10).font('Helvetica')
         .text(`Started: ${new Date(execution.startTime).toLocaleString()}`)
         .text(`Completed: ${new Date(execution.endTime).toLocaleString()}`)
         .text(`Duration: ${this.calculateDuration(execution.startTime, execution.endTime)}`)
         .moveDown();

      // Summary statistics
      doc.fontSize(14).font('Helvetica-Bold')
         .text('Summary Statistics')
         .moveDown(0.5);

      const summary = results.summary || {};
      const stats = [
        ['Videos Discovered', summary.totalVideosDiscovered || 0],
        ['Videos Downloaded', summary.totalVideosDownloaded || 0],
        ['Videos Processed', summary.totalVideosProcessed || 0],
        ['Videos Uploaded', summary.totalVideosUploaded || 0],
        ['Success Rate', `${(summary.successRate || 0).toFixed(2)}%`],
        ['Errors', summary.totalErrors || 0]
      ];

      let y = doc.y;
      stats.forEach(([label, value], index) => {
        doc.fontSize(10)
           .font('Helvetica-Bold').text(label, 50, y + (index * 20))
           .font('Helvetica').text(value.toString(), 200, y + (index * 20));
      });
      doc.moveDown(2);

      // Step Results
      if (results.stepResults && results.stepResults.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold')
           .text('Execution Steps')
           .moveDown(0.5);

        results.stepResults.forEach((step, index) => {
          doc.fontSize(12).font('Helvetica-Bold')
             .text(`Step ${index + 1}: ${step.stepType}`, { continued: true })
             .font('Helvetica')
             .text(step.success ? ' ✓' : ' ✗', { color: step.success ? 'green' : 'red' })
             .moveDown(0.3);

          doc.fontSize(10).font('Helvetica')
             .text(`Items processed: ${step.count || 0}`)
             .moveDown(0.5);
        });
      }

      // Errors
      if (results.errors && results.errors.length > 0) {
        doc.addPage();
        doc.fontSize(16).font('Helvetica-Bold').fillColor('red')
           .text('Errors Encountered')
           .fillColor('black')
           .moveDown();

        results.errors.forEach((error, index) => {
          doc.fontSize(10).font('Helvetica-Bold')
             .text(`Error ${index + 1}: ${error.type || 'Unknown'}`)
             .font('Helvetica')
             .text(`Step: ${error.step || 'N/A'}`)
             .text(`Message: ${error.message}`)
             .text(`Time: ${new Date(error.timestamp).toLocaleString()}`)
             .moveDown();
        });
      }

      // Footer
      doc.fontSize(8).font('Helvetica')
         .text('This report was automatically generated by AUTOLIVE System', 50, doc.page.height - 50, {
           align: 'center',
           width: doc.page.width - 100
         });

      doc.end();

      return new Promise((resolve) => {
        stream.on('finish', () => resolve(reportPath));
      });

    } catch (error) {
      console.error('Error generating PDF report:', error);
      throw error;
    }
  }

  async generateUploadReport(uploadData, options = {}) {
    try {
      const { format = 'excel', dateRange } = options;
      
      if (format === 'csv') {
        return await this.generateUploadCSV(uploadData);
      } else if (format === 'excel') {
        return await this.generateUploadExcel(uploadData);
      } else {
        return await this.generateUploadPDF(uploadData);
      }
    } catch (error) {
      console.error('Error generating upload report:', error);
      throw error;
    }
  }

  async generateUploadCSV(uploadData) {
    const reportPath = path.join(
      this.reportsPath,
      'csv',
      `uploads_${Date.now()}.csv`
    );

    const csvWriter = createObjectCsvWriter({
      path: reportPath,
      header: [
        { id: 'title', title: 'Video Title' },
        { id: 'platform', title: 'Platform' },
        { id: 'uploadDate', title: 'Upload Date' },
        { id: 'status', title: 'Status' },
        { id: 'views', title: 'Views' },
        { id: 'likes', title: 'Likes' },
        { id: 'comments', title: 'Comments' },
        { id: 'shares', title: 'Shares' },
        { id: 'url', title: 'URL' }
      ]
    });

    await csvWriter.writeRecords(uploadData);
    
    return reportPath;
  }

  async generateUploadExcel(uploadData) {
    const reportPath = path.join(
      this.reportsPath,
      'excel',
      `uploads_${Date.now()}.xlsx`
    );

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AUTOLIVE';
    workbook.created = new Date();

    // Summary sheet
    const summarySheet = workbook.addWorksheet('Summary');
    
    summarySheet.columns = [
      { header: 'Metric', key: 'metric', width: 30 },
      { header: 'Value', key: 'value', width: 20 }
    ];

    summarySheet.addRow({ metric: 'Total Videos', value: uploadData.length });
    summarySheet.addRow({ 
      metric: 'Successful Uploads', 
      value: uploadData.filter(v => v.status === 'completed').length 
    });
    summarySheet.addRow({ 
      metric: 'Failed Uploads', 
      value: uploadData.filter(v => v.status === 'failed').length 
    });
    summarySheet.addRow({ 
      metric: 'Total Views', 
      value: uploadData.reduce((sum, v) => sum + (v.views || 0), 0) 
    });
    summarySheet.addRow({ 
      metric: 'Total Engagement', 
      value: uploadData.reduce((sum, v) => sum + (v.likes || 0) + (v.comments || 0) + (v.shares || 0), 0) 
    });

    // Uploads sheet
    const uploadsSheet = workbook.addWorksheet('Uploads');
    
    uploadsSheet.columns = [
      { header: 'Title', key: 'title', width: 40 },
      { header: 'Platform', key: 'platform', width: 15 },
      { header: 'Upload Date', key: 'uploadDate', width: 20 },
      { header: 'Status', key: 'status', width: 15 },
      { header: 'Views', key: 'views', width: 10 },
      { header: 'Likes', key: 'likes', width: 10 },
      { header: 'Comments', key: 'comments', width: 10 },
      { header: 'Shares', key: 'shares', width: 10 },
      { header: 'URL', key: 'url', width: 50 }
    ];

    uploadData.forEach(video => {
      uploadsSheet.addRow({
        title: video.title,
        platform: video.platform,
        uploadDate: new Date(video.uploadDate).toLocaleString(),
        status: video.status,
        views: video.views || 0,
        likes: video.likes || 0,
        comments: video.comments || 0,
        shares: video.shares || 0,
        url: video.url
      });
    });

    // Format the sheet
    uploadsSheet.getRow(1).font = { bold: true };
    
    await workbook.xlsx.writeFile(reportPath);
    
    return reportPath;
  }

  async generateUploadPDF(uploadData) {
    const reportPath = path.join(
      this.reportsPath,
      'pdf',
      `uploads_${Date.now()}.pdf`
    );

    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    const stream = fs.createWriteStream(reportPath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).font('Helvetica-Bold')
       .text('AUTOLIVE Upload Report', { align: 'center' })
       .moveDown();

    doc.fontSize(10).font('Helvetica')
       .text(`Generated: ${new Date().toLocaleString()}`)
       .text(`Total Videos: ${uploadData.length}`)
       .moveDown();

    // Summary stats
    const successful = uploadData.filter(v => v.status === 'completed').length;
    const failed = uploadData.filter(v => v.status === 'failed').length;
    const totalViews = uploadData.reduce((sum, v) => sum + (v.views || 0), 0);
    const totalEngagement = uploadData.reduce(
      (sum, v) => sum + (v.likes || 0) + (v.comments || 0) + (v.shares || 0), 
      0
    );

    doc.fontSize(14).font('Helvetica-Bold')
       .text('Summary')
       .moveDown(0.5);

    const summaryData = [
      ['Successful Uploads:', successful],
      ['Failed Uploads:', failed],
      ['Success Rate:', `${((successful / uploadData.length) * 100).toFixed(2)}%`],
      ['Total Views:', totalViews],
      ['Total Engagement:', totalEngagement]
    ];

    let y = doc.y;
    summaryData.forEach(([label, value], index) => {
      doc.fontSize(10)
         .font('Helvetica-Bold').text(label, 50, y + (index * 20))
         .font('Helvetica').text(value.toString(), 200, y + (index * 20));
    });
    doc.moveDown(2);

    // Upload details
    doc.fontSize(14).font('Helvetica-Bold')
       .text('Upload Details')
       .moveDown();

    uploadData.slice(0, 50).forEach((video, index) => {
      if (doc.y > doc.page.height - 100) {
        doc.addPage();
      }

      doc.fontSize(12).font('Helvetica-Bold')
         .text(`${index + 1}. ${video.title}`)
         .fontSize(10).font('Helvetica')
         .text(`Platform: ${video.platform}`)
         .text(`Uploaded: ${new Date(video.uploadDate).toLocaleString()}`)
         .text(`Status: ${video.status}`)
         .text(`Views: ${video.views || 0} | Likes: ${video.likes || 0} | Comments: ${video.comments || 0}`)
         .moveDown();
    });

    if (uploadData.length > 50) {
      doc.text(`... and ${uploadData.length - 50} more videos`);
    }

    doc.end();

    return new Promise((resolve) => {
      stream.on('finish', () => resolve(reportPath));
    });
  }

  async generateAnalyticsReport(analyticsData, timeframe) {
    const reportPath = path.join(
      this.reportsPath,
      'pdf',
      `analytics_${timeframe}_${Date.now()}.pdf`
    );

    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    const stream = fs.createWriteStream(reportPath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).font('Helvetica-Bold')
       .text('AUTOLIVE Analytics Report', { align: 'center' })
       .moveDown();

    doc.fontSize(10).font('Helvetica')
       .text(`Generated: ${new Date().toLocaleString()}`)
       .text(`Timeframe: ${timeframe}`)
       .moveDown();

    // Key metrics
    doc.fontSize(14).font('Helvetica-Bold')
       .text('Key Metrics')
       .moveDown(0.5);

    const metrics = [
      ['Total Videos Processed', analyticsData.totalVideos || 0],
      ['Total Uploads', analyticsData.totalUploads || 0],
      ['Total Views', analyticsData.totalViews || 0],
      ['Total Engagement', analyticsData.totalEngagement || 0],
      ['Average Views per Video', analyticsData.avgViews || 0],
      ['Average Engagement Rate', `${(analyticsData.avgEngagementRate || 0).toFixed(2)}%`]
    ];

    let y = doc.y;
    metrics.forEach(([label, value], index) => {
      doc.fontSize(10)
         .font('Helvetica-Bold').text(label, 50, y + (index * 20))
         .font('Helvetica').text(value.toString(), 250, y + (index * 20));
    });
    doc.moveDown(2);

    // Platform breakdown
    if (analyticsData.byPlatform) {
      doc.fontSize(14).font('Helvetica-Bold')
         .text('Platform Breakdown')
         .moveDown();

      Object.entries(analyticsData.byPlatform).forEach(([platform, data]) => {
        doc.fontSize(12).font('Helvetica-Bold')
           .text(platform.toUpperCase())
           .fontSize(10).font('Helvetica')
           .text(`Videos: ${data.videos || 0}`)
           .text(`Views: ${data.views || 0}`)
           .text(`Engagement: ${data.engagement || 0}`)
           .moveDown();
      });
    }

    // Top performing videos
    if (analyticsData.topVideos && analyticsData.topVideos.length > 0) {
      doc.addPage();
      doc.fontSize(14).font('Helvetica-Bold')
         .text('Top Performing Videos')
         .moveDown();

      analyticsData.topVideos.forEach((video, index) => {
        doc.fontSize(12).font('Helvetica-Bold')
           .text(`${index + 1}. ${video.title}`)
           .fontSize(10).font('Helvetica')
           .text(`Views: ${video.views} | Engagement: ${video.engagement}`)
           .text(`Platform: ${video.platform}`)
           .moveDown(0.5);
      });
    }

    doc.end();

    return new Promise((resolve) => {
      stream.on('finish', () => resolve(reportPath));
    });
  }

  async generateDailyReport() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    // Get today's data
    const executions = await Execution.find({
      startTime: { $gte: today, $lt: tomorrow }
    });

    const uploads = await UploadReport.find({
      uploadDate: { $gte: today, $lt: tomorrow }
    });

    const videos = await Video.find({
      uploadedAt: { $gte: today, $lt: tomorrow }
    });

    const reportData = {
      date: today,
      executions: {
        total: executions.length,
        completed: executions.filter(e => e.status === 'completed').length,
        failed: executions.filter(e => e.status === 'failed').length,
        running: executions.filter(e => e.status === 'running').length
      },
      uploads: {
        total: uploads.length,
        successful: uploads.filter(u => u.status === 'completed').length,
        failed: uploads.filter(u => u.status === 'failed').length,
        videos: videos.length
      },
      performance: {
        totalViews: videos.reduce((sum, v) => sum + (v.statistics?.views || 0), 0),
        totalLikes: videos.reduce((sum, v) => sum + (v.statistics?.likes || 0), 0),
        totalComments: videos.reduce((sum, v) => sum + (v.statistics?.comments || 0), 0)
      }
    };

    const reportPath = path.join(
      this.reportsPath,
      'pdf',
      `daily_${today.toISOString().split('T')[0]}.pdf`
    );

    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    const stream = fs.createWriteStream(reportPath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).font('Helvetica-Bold')
       .text('AUTOLIVE Daily Report', { align: 'center' })
       .moveDown();

    doc.fontSize(10).font('Helvetica')
       .text(`Report Date: ${today.toLocaleDateString()}`)
       .text(`Generated: ${new Date().toLocaleString()}`)
       .moveDown();

    // Execution summary
    doc.fontSize(14).font('Helvetica-Bold')
       .text('Execution Summary')
       .moveDown(0.5);

    const execData = [
      ['Total Executions:', reportData.executions.total],
      ['Completed:', reportData.executions.completed],
      ['Failed:', reportData.executions.failed],
      ['Success Rate:', `${((reportData.executions.completed / Math.max(reportData.executions.total, 1)) * 100).toFixed(2)}%`]
    ];

    let y = doc.y;
    execData.forEach(([label, value], index) => {
      doc.fontSize(10)
         .font('Helvetica-Bold').text(label, 50, y + (index * 20))
         .font('Helvetica').text(value.toString(), 200, y + (index * 20));
    });
    doc.moveDown(2);

    // Upload summary
    doc.fontSize(14).font('Helvetica-Bold')
       .text('Upload Summary')
       .moveDown(0.5);

    const uploadData = [
      ['Total Uploads:', reportData.uploads.total],
      ['Successful:', reportData.uploads.successful],
      ['Failed:', reportData.uploads.failed],
      ['Success Rate:', `${((reportData.uploads.successful / Math.max(reportData.uploads.total, 1)) * 100).toFixed(2)}%`]
    ];

    y = doc.y;
    uploadData.forEach(([label, value], index) => {
      doc.fontSize(10)
         .font('Helvetica-Bold').text(label, 50, y + (index * 20))
         .font('Helvetica').text(value.toString(), 200, y + (index * 20));
    });
    doc.moveDown(2);

    // Performance metrics
    doc.fontSize(14).font('Helvetica-Bold')
       .text('Performance Metrics')
       .moveDown(0.5);

    const perfData = [
      ['Total Views:', reportData.performance.totalViews],
      ['Total Likes:', reportData.performance.totalLikes],
      ['Total Comments:', reportData.performance.totalComments],
      ['Total Engagement:', reportData.performance.totalLikes + reportData.performance.totalComments]
    ];

    y = doc.y;
    perfData.forEach(([label, value], index) => {
      doc.fontSize(10)
         .font('Helvetica-Bold').text(label, 50, y + (index * 20))
         .font('Helvetica').text(value.toString(), 200, y + (index * 20));
    });

    doc.end();

    return new Promise((resolve) => {
      stream.on('finish', () => resolve(reportPath));
    });
  }

  calculateDuration(start, end) {
    const duration = new Date(end) - new Date(start);
    const hours = Math.floor(duration / 3600000);
    const minutes = Math.floor((duration % 3600000) / 60000);
    const seconds = Math.floor((duration % 60000) / 1000);
    
    return `${hours}h ${minutes}m ${seconds}s`;
  }

  async cleanupOldReports(daysToKeep = 30) {
    try {
      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);

      const directories = ['pdf', 'csv', 'excel'];
      
      for (const dir of directories) {
        const dirPath = path.join(this.reportsPath, dir);
        const files = await fs.readdir(dirPath);

        for (const file of files) {
          const filePath = path.join(dirPath, file);
          const stats = await fs.stat(filePath);
          
          if (stats.mtime < cutoffDate) {
            await fs.remove(filePath);
            console.log(`Removed old report: ${file}`);
          }
        }
      }
    } catch (error) {
      console.error('Error cleaning up old reports:', error);
    }
  }
}

module.exports = new ReportGenerator();
